name: Publicar no PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build e Publicação
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build da lib
        run: |
          python setup.py sdist bdist_wheel

      - name: Publicar no PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*